In [5]:
import tensorflow as tf
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3])
mat2 = tf.ones([3,2])
mat3 = tf.fill([2,3], 15)
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[15 15 15]
 [15 15 15]]


In [8]:
import tensorflow as tf
mat0 = tf.constant([[2],[3],[4]])
mat1 = tf.zeros_like(mat0) # 以某矩阵为模板复制同等大小的全0矩阵
mat2 = tf.linspace(0.0,2.0,11) # 等分矩阵,0~2之间，分成11等分
mat3 = tf.random_uniform([2,3], -1, 2) # 随机矩阵，数据范围-1~2，矩阵大小2x3
with tf.Session() as sess:
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[ 0.22652769  0.17145729  1.0203738 ]
 [-0.9615575  -0.7484803  -0.47464144]]
